### ISSUE TITLE
Difference from built-in XUnit reporter

### ISSUE THREAD

**Issue by laughinghan** [michaelleeallen/mocha-junit-reporter#42]
I can't seem to find any documentation on what the difference is between this reporter and [the XUnit reporter built-into Mocha](http://mochajs.org/#undocumented-reporters)?

@junminstorage asked a similar question but appears to have gotten no answer.

**Comment by clayreimann** [comment]
[xUnit](https://xunit.github.io/) appears to be a different framework (it's for .NET, as opposed to [JUnit](http://junit.org/junit4/)'s Java focus). I can't seem to find the other question that you're referencing.

Reopen if I've misunderstood your question.

**Comment by laughinghan** [comment]
That's "xUnit.net". xUnit is the collective name for the unit testing frameworks derived from SUnit, popularized by JUnit: https://en.wikipedia.org/wiki/XUnit

Mocha's XUnit reporter appears to emit JUnit-compatible XML test reports, just like your reporter does, but I noticed that [CircleCI recommends your library](https://circleci.com/docs/test-metadata/#mochajs) and I was wondering what the difference was.

The other question I referenced was: https://github.com/michaelleeallen/mocha-junit-reporter/issues/30#issuecomment-209979691

**Comment by laughinghan** [comment]
Also I cannot reopen, only comment:

![image](https://cloud.githubusercontent.com/assets/225809/21596949/c4237b14-d110-11e6-8f3a-a57934955b7e.png)

> Reopen if I've misunderstood your question.

Is that intentional? Haha

**Comment by clayreimann** [comment]
Not intentional, but perhaps it's how github's permissions work for contributors vs. non-contributors. At any rate, you might be able to use the `xunit` reporter–I was not really aware of it before you mentioned it. If it works, great, but this library is intended to produce results that can be consumed by clients expecting JUnit style reports.

**Comment by gabegorelick** [comment]
Since there doesn't seem to be a resource that documents the differences between mocha-junit-reporter and mocha's builtin xunit reporter, I figured I would add something to this (old) discussion.

- The built in xunit reporter doesn't output suites. You get a single root `<testsuite>` element and then a series of `<testcase>` elements under that. Any suites in your code are implied by the `classname` attribute on `<testcase>`. Example:
```xml
<testsuite name="Mocha Tests" tests="1" failures="0" errors="0" skipped="0" timestamp="Sun, 10 May 2020 22:32:48 GMT" time="1.01">
<testcase classname="parent suite child suite" name="test name"/>
</testsuite>
```

- `mocha-junit-reporter` outputs a root `<testsuites>` element with `<testsuite>` elements directly underneath. Thus, each test suite, no matter how deeply nested, is hoisted to a top-level element under `<testsuites>`. So even though `mocha-junit-reporter` has more of a concept of suites than the built in xunit reporter, nested test suites aren't really a thing in the output and are only implied by `<testcase>` `name` attributes, which by default are built up from all ancestor suite names.
Example:
```xml
<testcase name="suite nested under another suite test name" time="0.0010" classname="test name"/>
```

- `mocha-junit-reporter` uses `classname` to indicate a testcase's name and `name` to indicate a testcase's full path in its suite hierarchy. The built in xunit reporter uses `classname` to indicate the full suite name hierarchy and `name` to indicate the test's name. This is much more intuitive IMHO.

`mocha-junit-reporter` example:
```xml
<testsuite name="parent suite" timestamp="2020-05-10T22:52:05" tests="1" file="/test.js" time="0.0000" failures="0">
    <testcase name="parent suite top-level test" time="0.0000" classname="top-level test"/>
</testsuite>
<testsuite name="nested suite" timestamp="2020-05-10T22:52:05" tests="1" file="/test.js" time="0.0000" failures="0">
    <testcase name="parent suite nested suite test in nested suite" time="0.0000" classname="test in nested suite"/>
</testsuite>
```

Built in xunit reporter example:
```xml
<testcase classname="parent suite" name="top-level test" time="0"/>
<testcase classname="parent suite nested suite" name="test in nested suite" time="0"/>
```


- `mocha-junit-reporter` outputs a (non-standard?) `file` attribute on `<testsuite>` elements. I suspect this is why CircleCI recommends `mocha-junit-reporter` since having an easy way to track which file a suite is defined in makes [test splitting](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-timing-data) much easier.

**Comment by laughinghan** [comment]
@gabegorelick Nice work!

@clayreimann You should add this info to the README!
